import React, { createContext, useState } from "react";

const initialCars = [
  {
    id: 1,
    name: "Koenigsegg",
    type: "Sport",
    fuelCapacity: "90L",
    transmission: "Manual",
    capacity: 2,
    price: "99.00",
    image: "../assets/image-1.png",
    favorite: true,
  },
  {
    id: 2,
    name: "Nissan GT - R",
    type: "Sport",
    fuelCapacity: "80L",
    transmission: "Manual",
    capacity: 2,
    price: "82.00",
    image: "../assets/image-2.png",
    favorite: false,
  },
  {
    id: 3,
    name: "Rolls-Royce",
    type: "Sport",
    fuelCapacity: "70L",
    transmission: "Manual",
    capacity: 4,
    price: "96.00",
    image: "../assets/image-3.png",
    favorite: false,
  },
  {
    id: 4,
    name: "All New Rush",
    type: "SUV",
    fuelCapacity: "70L",
    transmission: "Manual",
    capacity: 6,
    price: "76.00",
    image: "../assets/image-4.png",
    favorite: false,
  },
  {
    id: 5,
    name: "CR - V",
    type: "SUV",
    fuelCapacity: "80L",
    transmission: "Manual",
    capacity: 6,
    price: "80.00",
    image: "../assets/image-5.png",
    favorite: true,
  },
  {
    id: 6,
    name: "All New Terios",
    type: "SUV",
    fuelCapacity: "90L",
    transmission: "Manual",
    capacity: 6,
    price: "74.00",
    image: "../assets/image-6.png",
    favorite: false,
  },
  {
    id: 7,
    name: "MG ZX Exclusive",
    type: "Hatchback",
    fuelCapacity: "70L",
    transmission: "Electric",
    capacity: 4,
    price: "76.00",
    image: "../assets/image-7.png",
    favorite: false,
  },
  {
    id: 8,
    name: "New MG ZS",
    type: "SUV",
    fuelCapacity: "80L",
    transmission: "Manual",
    capacity: 6,
    price: "80.00",
    image: "../assets/image-8.png",
    favorite: false,
  },
  {
    id: 9,
    name: "MG ZX Excite",
    type: "Hatchback",
    fuelCapacity: "90L",
    transmission: "Electric",
    capacity: 4,
    price: "74.00",
    image: "../assets/image-9.png",
    favorite: true,
  },
  {
    id: 10,
    name: "Koenigsegg",
    type: "MPV",
    fuelCapacity: "10L",
    transmission: "Manual",
    capacity: 3,
    price: "20.00",
    image: "../assets/image-1.png",
    favorite: true,
  },
  {
    id: 11,
    name: "Nissan GT - R",
    type: "Coupe",
    fuelCapacity: "400L",
    transmission: "Manual",
    capacity: 2,
    price: "44.00",
    image: "../assets/image-2.png",
    favorite: true,
  },
  {
    id: 12,
    name: "Rolls-Royce",
    type: "Sport",
    fuelCapacity: "40L",
    transmission: "Manual",
    capacity: 6,
    price: "30.00",
    image: "../assets/image-3.png",
    favorite: false,
  },
  {
    id: 13,
    name: "All New Rush",
    type: "SUV",
    fuelCapacity: "80L",
    transmission: "Manual",
    capacity: 6,
    price: "100.00",
    image: "../assets/image-4.png",
    favorite: true,
  },
  {
    id: 14,
    name: "CR - V",
    type: "SUV",
    fuelCapacity: "80L",
    transmission: "Manual",
    capacity: 6,
    price: "30.00",
    image: "../assets/image-5.png",
    favorite: true,
  },
];

export const CarContext = createContext();

const CarProvider = ({ children }) => {
  const [cars, setCars] = useState(initialCars);
  const [filter, setFilter] = useState(false);
  return (
    <CarContext.Provider value={{ cars, setCars, filter, setFilter }}>
      {children}
    </CarContext.Provider>
  );
};

export default CarProvider;
